"""UTSA-specific opportunity provider with mock data."""
from __future__ import annotations

import uuid
from app.ingestion.base_provider import UniversityOpportunityProvider
from app.ingestion.normalization import normalize_opportunity


class UTSAProvider(UniversityOpportunityProvider):
    """
    UTSA opportunity provider.
    Currently returns mock data; set use_live_data=True to enable
    future live ingestion.
    """

    def __init__(self, use_live_data: bool = False):
        self.use_live_data = use_live_data
        self.source = "utsa"

    async def fetch_jobs(self) -> list[dict]:
        if self.use_live_data:
            return []  # Future: scrape UTSA Handshake / career portal
        return [normalize_opportunity(j, self.source, "job") for j in MOCK_JOBS]

    async def fetch_events(self) -> list[dict]:
        if self.use_live_data:
            return []
        return [normalize_opportunity(e, self.source, "event") for e in MOCK_EVENTS]

    async def fetch_research(self) -> list[dict]:
        if self.use_live_data:
            return []
        return [normalize_opportunity(r, self.source, "research") for r in MOCK_RESEARCH]

    async def fetch_organizations(self) -> list[dict]:
        if self.use_live_data:
            return []
        return [normalize_opportunity(o, self.source, "organization") for o in MOCK_ORGANIZATIONS]

    async def fetch_programs(self) -> list[dict]:
        if self.use_live_data:
            return []
        return [normalize_opportunity(p, self.source, "program") for p in MOCK_PROGRAMS]


# ── MOCK DATA ────────────────────────────────────────────────────────────────

MOCK_JOBS = [
    {
        "id": str(uuid.uuid4()),
        "title": "Software Engineering Intern",
        "organization": "USAA",
        "description": "Join USAA's technology team to build member-facing applications using Java, Spring Boot, and React. Work in an Agile environment with mentorship from senior engineers.",
        "skills": ["java", "spring boot", "react", "sql", "agile", "git"],
        "requirements": ["Pursuing CS or related degree", "Java experience", "GPA 3.0+"],
        "majors": ["Computer Science", "Software Engineering", "Information Technology"],
        "graduation_years": ["2026", "2027"],
        "location": "San Antonio, TX",
        "minimum_gpa": 3.0,
        "url": "https://www.usaajobs.com",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Cloud Engineering Intern",
        "organization": "Rackspace Technology",
        "description": "Work with Rackspace's cloud infrastructure team on AWS and Azure solutions. Participate in real customer projects and learn cloud architecture.",
        "skills": ["aws", "azure", "linux", "python", "docker", "networking"],
        "requirements": ["CS or related major", "Cloud computing interest", "Linux basics"],
        "majors": ["Computer Science", "Information Technology", "Cybersecurity"],
        "graduation_years": ["2026", "2027"],
        "location": "San Antonio, TX (Hybrid)",
        "url": "https://www.rackspace.com/careers",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Data Analytics Intern",
        "organization": "H-E-B Digital",
        "description": "Analyze retail data to drive business decisions. Work with SQL, Python, and Tableau to build dashboards and insights for H-E-B's digital transformation.",
        "skills": ["sql", "python", "tableau", "data analysis", "excel", "statistics"],
        "requirements": ["Business Analytics, CS, or Statistics major", "SQL proficiency"],
        "majors": ["Computer Science", "Data Science", "Statistics", "Business Analytics", "Information Systems"],
        "graduation_years": ["2026", "2027"],
        "location": "San Antonio, TX",
        "url": "https://careers.heb.com",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Cybersecurity Analyst Intern",
        "organization": "Booz Allen Hamilton",
        "description": "Support cybersecurity operations for government clients. Assist with vulnerability assessments, SIEM monitoring, and incident response.",
        "skills": ["network security", "siem", "vulnerability assessment", "linux", "incident response", "python"],
        "requirements": ["Cybersecurity or CS major", "Security+ preferred", "US Citizenship required"],
        "majors": ["Cybersecurity", "Computer Science", "Information Technology"],
        "graduation_years": ["2026", "2027"],
        "location": "San Antonio, TX",
        "work_authorization_required": True,
        "url": "https://www.boozallen.com/careers",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "IT Risk Analyst Intern",
        "organization": "Frost Bank",
        "description": "Support IT risk management and compliance initiatives. Work with the information security team on risk assessments and audit support.",
        "skills": ["risk management", "compliance", "data analysis", "excel", "communication"],
        "requirements": ["CS, IS, or Business major", "Interest in financial services"],
        "majors": ["Information Systems", "Computer Science", "Business", "Cybersecurity"],
        "graduation_years": ["2026", "2027"],
        "location": "San Antonio, TX",
        "url": "https://www.frostbank.com/careers",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Full Stack Developer Intern",
        "organization": "Accenture",
        "description": "Build client solutions using modern web technologies. Collaborate with global teams on enterprise applications.",
        "skills": ["javascript", "react", "node.js", "sql", "git", "agile", "html", "css"],
        "requirements": ["CS or SE major", "Web development experience", "GPA 3.2+"],
        "majors": ["Computer Science", "Software Engineering"],
        "graduation_years": ["2026", "2027"],
        "location": "San Antonio, TX (Hybrid)",
        "minimum_gpa": 3.2,
        "url": "https://www.accenture.com/careers",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Machine Learning Research Intern",
        "organization": "Southwest Research Institute (SwRI)",
        "description": "Contribute to applied ML research projects in autonomous systems, signal processing, or NLP. Work alongside PhD researchers.",
        "skills": ["python", "machine learning", "pytorch", "tensorflow", "data analysis", "research"],
        "requirements": ["CS or Math major", "ML coursework", "Research interest"],
        "majors": ["Computer Science", "Mathematics", "Data Science"],
        "graduation_years": ["2026", "2027"],
        "location": "San Antonio, TX",
        "url": "https://www.swri.org/careers",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Energy Systems Developer",
        "organization": "CPS Energy",
        "description": "Develop software for energy grid management and smart meter data analysis. Full-time position for recent graduates.",
        "skills": ["python", "sql", "data analysis", "scada", "networking", "linux"],
        "requirements": ["BS in CS or EE", "Python experience"],
        "majors": ["Computer Science", "Electrical Engineering", "Software Engineering"],
        "graduation_years": ["2025", "2026"],
        "location": "San Antonio, TX",
        "url": "https://www.cpsenergy.com/careers",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "DevOps Engineer Intern",
        "organization": "Valero Energy",
        "description": "Support CI/CD pipelines and cloud infrastructure for Valero's digital operations team. Learn enterprise DevOps practices.",
        "skills": ["docker", "kubernetes", "ci/cd", "aws", "linux", "python", "terraform"],
        "requirements": ["CS major", "Linux experience", "Interest in DevOps"],
        "majors": ["Computer Science", "Information Technology"],
        "graduation_years": ["2026", "2027"],
        "location": "San Antonio, TX",
        "url": "https://www.valero.com/careers",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Data Engineer",
        "organization": "USAA",
        "description": "Build and maintain data pipelines for financial analytics. Full-time role working with Spark, Airflow, and cloud data platforms.",
        "skills": ["python", "sql", "spark", "airflow", "aws", "data warehousing", "etl", "kafka"],
        "requirements": ["BS in CS or related", "Python and SQL proficiency", "2+ years experience or strong internship"],
        "majors": ["Computer Science", "Data Science", "Information Systems"],
        "graduation_years": ["2025", "2026"],
        "location": "San Antonio, TX (Hybrid)",
        "url": "https://www.usaajobs.com",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Student Worker — IT Help Desk",
        "organization": "UTSA Office of Information Technology",
        "description": "Provide technical support to UTSA students, faculty, and staff. Troubleshoot hardware, software, and network issues.",
        "skills": ["troubleshooting", "communication", "windows", "networking", "customer service"],
        "requirements": ["Current UTSA student", "Basic IT knowledge"],
        "majors": [],
        "graduation_years": ["2026", "2027", "2028", "2029"],
        "location": "UTSA Main Campus, San Antonio, TX",
        "url": "https://www.utsa.edu/oit",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Student Research Assistant — Computer Science",
        "organization": "UTSA Department of Computer Science",
        "description": "Assist faculty with research in AI, cybersecurity, or systems. Gain hands-on research experience and mentorship.",
        "skills": ["python", "research", "data analysis", "machine learning"],
        "requirements": ["CS major", "GPA 3.0+", "Completed Data Structures"],
        "majors": ["Computer Science"],
        "graduation_years": ["2026", "2027", "2028"],
        "location": "UTSA Main Campus",
        "minimum_gpa": 3.0,
        "url": "https://cs.utsa.edu/research",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Business Intelligence Analyst",
        "organization": "Frost Bank",
        "description": "Create dashboards and reports to support executive decision-making. Work with Power BI, SQL, and enterprise data.",
        "skills": ["power bi", "sql", "data visualization", "excel", "business analysis", "communication"],
        "requirements": ["BS in IS, Analytics, or CS", "SQL and BI tool experience"],
        "majors": ["Information Systems", "Business Analytics", "Computer Science"],
        "graduation_years": ["2025", "2026"],
        "location": "San Antonio, TX",
        "url": "https://www.frostbank.com/careers",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Mobile App Developer Intern",
        "organization": "H-E-B Digital",
        "description": "Build features for H-E-B's customer-facing mobile apps. Work with React Native and modern mobile development practices.",
        "skills": ["react native", "javascript", "typescript", "mobile development", "rest api", "git"],
        "requirements": ["CS or SE major", "Mobile dev experience preferred"],
        "majors": ["Computer Science", "Software Engineering"],
        "graduation_years": ["2026", "2027"],
        "location": "San Antonio, TX",
        "url": "https://careers.heb.com",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Junior Product Manager",
        "organization": "Rackspace Technology",
        "description": "Support product strategy and roadmap for cloud services. Bridge engineering and business teams.",
        "skills": ["product management", "agile", "communication", "data analysis", "jira", "user research"],
        "requirements": ["BS in CS, Business, or related", "Strong communication skills"],
        "majors": ["Computer Science", "Business", "Information Systems"],
        "graduation_years": ["2025", "2026"],
        "location": "San Antonio, TX (Hybrid)",
        "url": "https://www.rackspace.com/careers",
    },
]

MOCK_EVENTS = [
    {
        "id": str(uuid.uuid4()),
        "title": "UTSA Fall Career Fair 2026",
        "organization": "UTSA Career Center",
        "description": "Meet 100+ employers from technology, engineering, business, and healthcare. Bring your resume and dress professionally.",
        "skills": ["networking", "communication", "interview skills"],
        "location": "UTSA Convocation Center",
        "url": "https://www.utsa.edu/careercenter",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Tech Industry Panel: Breaking into Software Engineering",
        "organization": "UTSA ACM Chapter",
        "description": "Panel discussion with engineers from USAA, Rackspace, and H-E-B on how to land your first software role.",
        "skills": ["communication", "networking"],
        "location": "UTSA NPB 2.124",
        "url": "https://utsa-acm.org",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "AWS Cloud Workshop",
        "organization": "UTSA Cloud Computing Club",
        "description": "Hands-on workshop covering EC2, S3, Lambda, and IAM. Build and deploy a serverless application.",
        "skills": ["aws", "cloud computing", "serverless", "lambda"],
        "location": "UTSA BSE 2.102",
        "url": "https://utsa-cloudclub.org",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "RowdyHacks 2026",
        "organization": "RowdyHacks",
        "description": "UTSA's annual hackathon. Build something amazing in 24 hours. Open to all majors and skill levels.",
        "skills": ["rapid prototyping", "teamwork", "presentation", "full stack"],
        "location": "UTSA San Pedro I",
        "url": "https://rowdyhacks.org",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Cybersecurity Career Night",
        "organization": "UTSA Center for Infrastructure Assurance and Security",
        "description": "Network with cybersecurity professionals and learn about career paths in information security.",
        "skills": ["cybersecurity", "networking", "communication"],
        "location": "UTSA Downtown Campus",
        "url": "https://cias.utsa.edu",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Data Science in Industry Workshop",
        "organization": "UTSA Data Science Club",
        "description": "Learn how data science is applied at companies like USAA and H-E-B. Hands-on exercises included.",
        "skills": ["python", "data analysis", "machine learning", "sql"],
        "location": "UTSA NPB 3.120",
        "url": "https://utsa-datasci.org",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Resume Review Workshop",
        "organization": "UTSA Career Center",
        "description": "Get one-on-one feedback on your resume from career advisors and industry professionals.",
        "skills": ["communication", "technical writing"],
        "location": "UTSA Student Union",
        "url": "https://www.utsa.edu/careercenter",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Google Developer Student Club: Flutter Workshop",
        "organization": "GDSC UTSA",
        "description": "Build a cross-platform mobile app with Flutter and Dart in this beginner-friendly workshop.",
        "skills": ["flutter", "dart", "mobile development", "ui design"],
        "location": "UTSA BSE 1.102",
        "url": "https://gdsc.community.dev/utsa",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Women in Tech Networking Mixer",
        "organization": "UTSA Society of Women Engineers",
        "description": "Connect with women in technology fields. Features speakers from USAA, Accenture, and SwRI.",
        "skills": ["networking", "communication", "leadership"],
        "location": "UTSA Engineering Building",
        "url": "https://swe-utsa.org",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Mock Technical Interview Day",
        "organization": "UTSA ACM & Career Center",
        "description": "Practice technical interviews with industry volunteers. Covers data structures, algorithms, and behavioral questions.",
        "skills": ["algorithms", "data structures", "communication", "problem solving"],
        "location": "UTSA NPB 2.124",
        "url": "https://utsa-acm.org",
    },
]

MOCK_RESEARCH = [
    {
        "id": str(uuid.uuid4()),
        "title": "AI for Healthcare — Dr. Martinez Lab",
        "organization": "UTSA CS Department",
        "description": "Research applying deep learning to medical image analysis. Experience with Python and PyTorch required.",
        "skills": ["python", "pytorch", "deep learning", "computer vision", "research"],
        "requirements": ["CS or DS major", "ML coursework", "GPA 3.2+"],
        "majors": ["Computer Science", "Data Science"],
        "location": "UTSA Main Campus",
        "minimum_gpa": 3.2,
        "url": "https://cs.utsa.edu/research/ai-health",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Cybersecurity Research — CIAS Lab",
        "organization": "UTSA Center for Infrastructure Assurance and Security",
        "description": "Research in network security, malware analysis, or digital forensics. UTSA is a top-ranked cybersecurity program.",
        "skills": ["network security", "linux", "python", "research", "malware analysis"],
        "requirements": ["Cybersecurity or CS major", "Network security coursework"],
        "majors": ["Cybersecurity", "Computer Science"],
        "location": "UTSA Downtown Campus",
        "url": "https://cias.utsa.edu/research",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Natural Language Processing Research",
        "organization": "UTSA NLP Lab",
        "description": "Work on text classification, sentiment analysis, or language model research with faculty advisor.",
        "skills": ["python", "nlp", "machine learning", "tensorflow", "research"],
        "requirements": ["CS major", "ML/NLP interest", "Python proficiency"],
        "majors": ["Computer Science", "Data Science"],
        "location": "UTSA Main Campus",
        "url": "https://cs.utsa.edu/research/nlp",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Cloud Computing Performance Research",
        "organization": "UTSA Systems Lab",
        "description": "Research cloud computing performance optimization and distributed systems. Involves benchmarking and analysis.",
        "skills": ["cloud computing", "linux", "python", "distributed systems", "research"],
        "requirements": ["CS major", "OS and Networks coursework"],
        "majors": ["Computer Science"],
        "location": "UTSA Main Campus",
        "url": "https://cs.utsa.edu/research/systems",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Data Analytics Research — Business College",
        "organization": "UTSA Alvarez College of Business",
        "description": "Apply analytics techniques to business and economic data. Collaborate with business faculty on publications.",
        "skills": ["r", "statistics", "data analysis", "research", "excel"],
        "requirements": ["IS, DS, or Statistics major", "Statistics coursework"],
        "majors": ["Information Systems", "Data Science", "Statistics", "Business Analytics"],
        "location": "UTSA Main Campus",
        "url": "https://business.utsa.edu/research",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "NSF REU: Intelligent Systems Summer Program",
        "organization": "UTSA CS Department / NSF",
        "description": "10-week paid summer research program in AI and intelligent systems. Open to undergraduates nationwide.",
        "skills": ["python", "machine learning", "research", "data analysis"],
        "requirements": ["Undergraduate student", "CS or related major", "US Citizen or Permanent Resident"],
        "majors": ["Computer Science", "Data Science", "Mathematics"],
        "location": "UTSA Main Campus",
        "work_authorization_required": True,
        "url": "https://cs.utsa.edu/reu",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "IoT Security Research",
        "organization": "UTSA Embedded Systems Lab",
        "description": "Research security vulnerabilities in IoT devices. Hands-on work with hardware and network protocols.",
        "skills": ["embedded systems", "network security", "c", "python", "research"],
        "requirements": ["CS or CE major", "Embedded systems or security coursework"],
        "majors": ["Computer Science", "Computer Engineering", "Cybersecurity"],
        "location": "UTSA Main Campus",
        "url": "https://cs.utsa.edu/research/iot",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Software Engineering Practices Research",
        "organization": "UTSA SE Research Group",
        "description": "Study software engineering best practices, code quality metrics, and developer productivity.",
        "skills": ["python", "research", "data analysis", "software engineering", "git"],
        "requirements": ["CS or SE major", "Completed Software Engineering course"],
        "majors": ["Computer Science", "Software Engineering"],
        "location": "UTSA Main Campus",
        "url": "https://cs.utsa.edu/research/se",
    },
]

MOCK_ORGANIZATIONS = [
    {
        "id": str(uuid.uuid4()),
        "title": "Association for Computing Machinery (ACM) — UTSA Chapter",
        "organization": "ACM UTSA",
        "description": "Programming competitions, tech talks, workshops, and networking events for CS students.",
        "skills": ["algorithms", "data structures", "networking", "teamwork"],
        "url": "https://utsa-acm.org",
        "location": "UTSA Main Campus",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "IEEE Student Branch — UTSA",
        "organization": "IEEE UTSA",
        "description": "Professional development, workshops, and industry connections for engineering students.",
        "skills": ["networking", "systems", "leadership", "technical skills"],
        "url": "https://ieee-utsa.org",
        "location": "UTSA Main Campus",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Society of Women Engineers (SWE) — UTSA",
        "organization": "SWE UTSA",
        "description": "Support network and professional development for women in engineering and technology.",
        "skills": ["networking", "leadership", "communication", "mentoring"],
        "url": "https://swe-utsa.org",
        "location": "UTSA Main Campus",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "National Society of Black Engineers (NSBE) — UTSA",
        "organization": "NSBE UTSA",
        "description": "Professional development, mentoring, and community for Black engineering students.",
        "skills": ["networking", "leadership", "communication", "teamwork"],
        "url": "https://nsbe-utsa.org",
        "location": "UTSA Main Campus",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Google Developer Student Club — UTSA",
        "organization": "GDSC UTSA",
        "description": "Hands-on workshops using Google technologies. Build projects, attend events, and grow your skills.",
        "skills": ["google cloud", "flutter", "android", "machine learning", "web development"],
        "url": "https://gdsc.community.dev/utsa",
        "location": "UTSA Main Campus",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Cybersecurity Club — UTSA",
        "organization": "CyberSec UTSA",
        "description": "CTF competitions, security workshops, and networking with cybersecurity professionals.",
        "skills": ["network security", "penetration testing", "linux", "ctf"],
        "url": "https://cybersec-utsa.org",
        "location": "UTSA Main Campus",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Data Science Club — UTSA",
        "organization": "DS Club UTSA",
        "description": "Data projects, Kaggle competitions, and workshops in data science and analytics.",
        "skills": ["python", "machine learning", "sql", "data visualization", "statistics"],
        "url": "https://datasci-utsa.org",
        "location": "UTSA Main Campus",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Blockchain and Web3 Club — UTSA",
        "organization": "Blockchain UTSA",
        "description": "Explore blockchain technology, smart contracts, and decentralized applications.",
        "skills": ["blockchain", "solidity", "web3", "javascript", "cryptography"],
        "url": "https://blockchain-utsa.org",
        "location": "UTSA Main Campus",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Artificial Intelligence Club — UTSA",
        "organization": "AI Club UTSA",
        "description": "Paper reading groups, AI project teams, and guest speakers in artificial intelligence.",
        "skills": ["python", "machine learning", "deep learning", "nlp", "research"],
        "url": "https://ai-utsa.org",
        "location": "UTSA Main Campus",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Hispanic Engineers & Scientists (SHPE) — UTSA",
        "organization": "SHPE UTSA",
        "description": "Professional development and community for Hispanic students in STEM fields.",
        "skills": ["networking", "leadership", "communication", "mentoring"],
        "url": "https://shpe-utsa.org",
        "location": "UTSA Main Campus",
    },
]

MOCK_PROGRAMS = [
    {
        "id": str(uuid.uuid4()),
        "title": "UTSA Honors College — Undergraduate Research",
        "organization": "UTSA Honors College",
        "description": "Honors students complete a thesis or capstone research project with faculty mentorship.",
        "skills": ["research", "critical thinking", "academic writing", "presentation"],
        "requirements": ["Honors College membership", "GPA 3.5+"],
        "minimum_gpa": 3.5,
        "url": "https://honors.utsa.edu",
        "location": "UTSA Main Campus",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "UTSA Roadrunner Leadership Program",
        "organization": "UTSA Student Leadership Center",
        "description": "Develop leadership skills through workshops, community service, and mentorship with campus leaders.",
        "skills": ["leadership", "communication", "project management", "teamwork"],
        "url": "https://www.utsa.edu/leadership",
        "location": "UTSA Main Campus",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "CS Peer Mentorship Program",
        "organization": "UTSA CS Department",
        "description": "Upper-classmen mentor freshmen and sophomores in CS coursework and career planning.",
        "skills": ["mentoring", "communication", "technical knowledge", "leadership"],
        "requirements": ["CS major", "Junior or Senior standing"],
        "url": "https://cs.utsa.edu/mentorship",
        "location": "UTSA Main Campus",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "UTSA Innovation & Entrepreneurship Program",
        "organization": "UTSA Center for Innovation & Entrepreneurship",
        "description": "Turn your tech ideas into startups. Workshops, pitch competitions, and incubator access.",
        "skills": ["entrepreneurship", "product management", "presentation", "business strategy"],
        "url": "https://cie.utsa.edu",
        "location": "UTSA Main Campus",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "UTSA Career Center — Career Coaching Program",
        "organization": "UTSA Career Center",
        "description": "One-on-one coaching with career advisors. Resume review, interview prep, and career exploration.",
        "skills": ["communication", "interview skills", "networking"],
        "url": "https://www.utsa.edu/careercenter",
        "location": "UTSA Main Campus",
    },
]
